services:
  express-server:
    build:
      context: ./express-server
      dockerfile: Dockerfile
    environment:
      FASTAPI_SERVER: ${FASTAPI_SERVER}
      HASH_SALT: ${HASH_SALT}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_SENDER: ${MAIL_SENDER}
      OTP_SECRET: ${OTP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - postgres-server

  fastapi-server:
    build:
      context: ./fastapi-server
      dockerfile: Dockerfile
    environment:
      MODEL_NAME: ${MODEL_NAME}

  postgres-server:
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./psql-data:/var/lib/postgresql/data"
