services:
  nextjs-server:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: next-server
    ports:
      - "3000:3000"

  express-server:
    build:
      context: ./express-server
      dockerfile: Dockerfile
    container_name: express-server
    environment:
      FASTAPI_SERVER: ${FASTAPI_SERVER}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      HASH_SALT: ${HASH_SALT}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_SENDER: ${MAIL_SENDER}
      OTP_SECRET: ${OTP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5000:5000"
    depends_on:
      - postgres-server

  fastapi-server:
    build:
      context: ./fastapi-server
      dockerfile: Dockerfile
    container_name: fastapi-server

  postgres-server:
    image: postgres:17.2-alpine3.21
    container_name: postgres-server
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./psql-data:/var/lib/postgresql/data"
