apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gemini-secret
  namespace: legislative-summarization
spec:
  encryptedData:
    GEMINI_API_KEY: AgBpokcUPJZWo16JsMiKg/cuKgJyxYmy9cmVAT6pyrniVQ21xXHsBq5bbbQACW23rJlVYMysotWQRT15mhQELW5Bf2KQRTzH4KAkUXvKtS/+y8tML3jeGG5NwoY+/GZWQvhGWW/B9a18NE1W5zhtQosX5NYW0LWpTkEmF3Ggwhdvz4E51nRXp+u3wpV1zR5gJzmc2HgG5cb9lK3QYPg4hmK4NebM6GoI2eF9IOQoNp7nP97PYVkQOzdH53gd73m4JhSauGYCQHt2qpsUiwepDuVlSYOgI0UIULHGNDZqvqSbkEXhMaTtbIvvksSQqeFnUwVNaLGaIoIH3/hJtTY6GRBpQddk9E1UNcWFMZuGoNpi+NAMS2t8UptKHg1KzQmDof2bqGg1Dt0IdPMi5858BMkrEB4sHoU6FKdkOlaKW3pDkxtmWoCxd1gAGPuBmILJKWVmtMwpZv7jjSzVpAtMDeWXrzzS2zPpcNA8J9in40lw0aU3bRAf4NmlFGcV3OHXV5BM6deBtynztKBI73aJEYx3yOw+Ap/DfK+ZTm+znSjBCORFrUgvzlKkJmc85n3/oj1tWfuOqvJVwJcoX/3iVdmG3vFrmqj4ZKZMZtHVfhmC1VHBSrsb35FR9kTEoayqXDTB712rrGp89LK40ZWumdLjYNigLK0WZ3o7VbVY1ZStcayZo6YDXfQBd5qQNjomnRio4eV97C/R28Ay1HbdxqNO4G8g/R71o5cHNASRJmnoh5hU/Q/+QSQ=
  template:
    metadata:
      name: gemini-secret
      namespace: legislative-summarization
    type: Opaque
