apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/component: express-server
    includeTemplates: true
    fields:
      - path: spec/selector/matchLabels
        kind: Deployment
        create: true
      - path: spec/selector
        kind: Service
        create: true
resources:
  - deployment.yaml
  - service.yaml
  - auth-secret.yaml
  - gemini-secret.yaml
  - mail-secret.yaml
  - db-credentials.yaml
  - configmap.yaml
  - networkpolicy.yaml
