apiVersion: v1
kind: Service
metadata:
  name: express-server
  labels:
    app: express-server
spec:
  type: ClusterIP
  selector:
    app: express-server
  ports:
    - port: 5000
      targetPort: 5000
