name: Build and Push to GHCR

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docker-build-push.yaml
      - express-server/**/*
      - fastapi-server/**/*
      - next-server/**/*
  workflow_dispatch:

env:
  IMAGE_PREFIX: ghcr.io/whyredfire/ls

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    strategy:
      matrix:
        arch: [amd64, arm64]
        service: [next-server, express-server, fastapi-server]
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image for ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service }}
          push: true
          platforms: linux/${{ matrix.arch }}
          tags: ${{ env.IMAGE_PREFIX }}-${{ matrix.service }}:${{ github.sha }}-${{ matrix.arch }}
          cache-from: type=gha,scope=${{ matrix.service }}-${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=${{ matrix.service }}-${{ matrix.arch }}

  create-multiarch:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create multi-arch manifests
        run: |
          services=("next-server" "express-server" "fastapi-server")

          for service in "${services[@]}"; do
            echo "Creating manifest for $service..."

            docker buildx imagetools create \
              -t ${{ env.IMAGE_PREFIX }}-$service:latest \
              -t ${{ env.IMAGE_PREFIX }}-$service:${{ github.sha }} \
              ${{ env.IMAGE_PREFIX }}-$service:${{ github.sha }}-amd64 \
              ${{ env.IMAGE_PREFIX }}-$service:${{ github.sha }}-arm64
          done

  update-manifests:
    needs: create-multiarch
    runs-on: ubuntu-slim
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Update image tags
        run: |
          yq -i ".spec.template.spec.containers[0].image = \"ghcr.io/whyredfire/ls-next-server:${GITHUB_SHA}\"" k8s/next-server/deployment.yaml
          yq -i ".spec.template.spec.containers[0].image = \"ghcr.io/whyredfire/ls-express-server:${GITHUB_SHA}\"" k8s/express-server/deployment.yaml
          yq -i ".spec.template.spec.containers[0].image = \"ghcr.io/whyredfire/ls-fastapi-server:${GITHUB_SHA}\"" k8s/fastapi-server/deployment.yaml

      - name: Commit to repo
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit_message: "k8s: Bump images to ${{ github.sha }} [no ci]"
          file_pattern: "k8s/**/deployment.yaml"
